name: cs3portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: HorizonType
      fonts:
        - asset: assets/fonts/Horizon Type - AcherusFeral-Bold.otf
        - asset: assets/fonts/Horizon Type - AcherusFeral-Light.otf
  assets:
    - assets/images/

